# Generated by Django 4.1.5 on 2023-05-11 08:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("Title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Title", models.CharField(max_length=255)),
                ("Description", models.CharField(max_length=255)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "AvaliableDate",
                    models.DateField(
                        default=datetime.datetime(2023, 5, 11, 15, 40, 58, 529175)
                    ),
                ),
                ("StockQuantity", models.DecimalField(decimal_places=0, max_digits=10)),
                ("Image_1", models.CharField(max_length=512)),
                ("Image_2", models.CharField(max_length=512)),
                ("Image_3", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MeunTitle", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MyStore.category",
                    ),
                ),
            ],
        ),
    ]
