# Generated by Django 4.1.5 on 2023-05-12 06:10

import MyStore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MyStore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Promotion_Id", models.SmallIntegerField(default=0)),
                ("Product_Id", models.SmallIntegerField(default=0)),
                (
                    "User",
                    models.CharField(
                        max_length=255,
                        validators=[MyStore.models.Promotion.validate_user],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="menu",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="Product_Id",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="AvaliableDate",
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.AddField(
            model_name="product",
            name="Promotion_Id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="MyStore.promotion",
            ),
        ),
    ]
