# Generated by Django 4.1.5 on 2023-05-12 06:33

import MyStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyStore", "0002_promotion_remove_menu_category_product_product_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "UserName",
                    models.CharField(
                        max_length=255, validators=[MyStore.models.Users.validate_user]
                    ),
                ),
                ("SiteID", models.SmallIntegerField(default=0)),
            ],
        ),
    ]
